project:
  type: website

website:
  title: "Job Market Analysis"
  site-url: "https://chialingsung.github.io/ad688-employability-sp25A1-group8/"
  favicon: reference/icon.png
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: introduction.qmd
        text: "ğŸ“– Introduction"
      - href: data_analysis.ipynb
        text: "ğŸ§¹ Data Cleaning"
      - href: eda.ipynb
        text: "ğŸ“Š EDA"
      - href: skill_gap_analysis.ipynb
        text: "ğŸ’¼ Skill Gap"
      - href: ml_methods.ipynb
        text: "ğŸ¤– ML Methods"
      - href: regression_methods.ipynb
        text: "ğŸ“ˆ Regression"

  page-footer:
    left: "Â© 2025 Team 8 | Boston University"
    right:
      - icon: github
        href: https://github.com/ChialingSung/ad688-employability-sp25A1-group8
        text: "GitHub"

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    includes:
      in-header: reference/fonts.html
    smooth-scroll: true
    link-external-newwindow: true

execute:
  echo: true
  eval: true
